### ISSUE TITLE
Replace custom GitHub client with official GraphQL one

### ISSUE THREAD

**Issue by 13xforever** [RPCS3/discord-bot#420]
Right now we're using a tiny custom-built client that is using older REST API version. It would be nice to migrate to a properly supported official client. This would also help in the future if we'll have to use authentication for increased request limits.

**Comment by grantwinney** [comment]
I'd like to have a go at this. There's the official [octokit.net](https://github.com/octokit/octokit.net) library, which seems fairly established and I imagine is built on REST. Then there's the official [octokit.graphql.net](https://github.com/octokit/octokit.graphql.net) package, which should be great one day, but...

> This software is currently beta. There are few things left, and there might be bugs - be warned!

Would you like someone to look into migrating to one of these, or did you have something else in mind?

**Comment by grantwinney** [comment]
If you decide to go with the octokit.net library, would you want to use the `PullRequest` class (for example) that they define, or translate it into your existing `PrInfo` class?

**Comment by grantwinney** [comment]
I made a PR, which at least can be a discussion point. It could _technically_ be merged, but there are issues that should probably be addressed first. Let me know what you think, and I'll understand if it's not the direction you want to go.

I'm in the process of trying to learn more about GraphQL in general, and GitHub's in particular since it seems they've got the most mature and well documented implementation around, but it's unfortunate their .NET client is still beta.

**Comment by 13xforever** [comment]
I'd prefer to migrate to official v3 client, even if it's in beta (half of the libraries we use are beta anyway).
There's no point in keeping our custom pocos, there shouldn't be too many places that would require to change the code (but that could be discussed if converting is easier).

I'll look at the pr in a few hours.

**Comment by grantwinney** [comment]
I'm still here btw. I have _some_ of the replacement done, but I'm not sure their GraphQL NuGet package can replace everything. Maybe I'll submit a draft PR in the next day or two so at least you'll have something to look at.
